### ISSUE TITLE
可以在React组件外部订阅状态更新吗?

### ISSUE THREAD

**Issue by czfshine** [forsigner/stook#19]
这个项目挺好的,但是有个问题,目前我使用Redux一部分原因是为了实现React内和外部另外一个渲染程序(WebGL)的数据双向绑定的,看了下API文档,好像在外部只能读取指定状态,没法订阅更新.
或者提供个Api,直接暴露原始Redux的stroe对象.:joy:

**Comment by forsigner** [comment]
@czfshine 可以的，这个场景不常见，这个文档没写，内部有 store 更新的发布订阅，使用方法如下：
```js
import { onStoreUpdate } from 'stook'

onStoreUpdate(({ key, nextState }) => {
  // Do something
  console.log(key, nextState)
})
```
