### ISSUE TITLE
useStore能否支持useSelector

### ISSUE THREAD

**Issue by huqc2513** [forsigner/stook#32]
目前的useStore只要组件订阅了key, setState之后就会将发布订阅队列全部执行渲染，即使组件中没有用到store中的某些数据，能否实现类似redux的useSelector式API呢，另外还有一个问题就是目前这种方案，useStore中的数据初始化是在第二个参数中，两个组件订阅相同的key,初始化的数据将会以第一个先订阅为准，这样没约束规范吧，是否需要加一个store初始化的步骤呢

**Comment by forsigner** [comment]
暂时没有计划支持
